### ISSUE TITLE
Newly created tables and following content not visible in problem thumbnail/preview

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#21] opened 2015-08-17 20:19 UTC
Steps to reproduce:
Log into PA account and navigate to the Play Area
Select a question bank
Click "Edit" on a problem or write a new one.
Create a simple table with no headers, captions or labels.
Include some text both before and after the table.
Save the problem

RESULT:
In both the problem thumbnail and the PDF preview, neither the table nor anything that comes after it is displayed. 

Similar results are noted  when table headers or labels are included. The first row of table data may appear but the rest of the problem appears blank in both the thumbnail and PDF preview.

Have not noted any problems editing previously existing tables.

**Comment by Reinmar** [comment] 2015-08-18 09:48
Hmm... I noticed that there's no `&zwnj;` character in the data produced by the new editor. That, however, was my mistake, because the character is there – it just isn't encoded (so it's invisible).

To fix that you can either enable the `htmlentities` plugin or fix the PDF generator so it can recognise non-encoded entities.

**Comment by gcortright** [comment] 2015-08-18 20:54
@Reinmar will include the htmlentities plugin.

**Comment by gcortright** [comment] 2015-08-19 17:47
@Reinmar I didn't find any plugin by the name of `htmlentities`, but did find one named `entities, which _appears_ to be the correct one. However, after including the plugin in build-config.js, getting a new build and deploying it, I am still able to reproduce the issue.

**Comment by Reinmar** [comment] 2015-08-27 12:58
Sorry for the confusion. You're right that this plugin is called `entities`. However, it seems to work for me:

```
CKEDITOR.instances.editor.setData( '<p>f&zwnj;g</p>' );

CKEDITOR.instances.editor.getData();
"<p>f&zwnj;g</p>"
```

Could you deploy a new version with 1a67ba1 so I can see it live? If the data produced by CKE3 and CKE4 for this case will be identical, then the issue must be somewhere else.

**Comment by Reinmar** [comment] 2015-08-27 16:29
I'm closing this issue to keep the list clean. Reopen if this is still a problem.

**Closed by Reinmar** 2015-08-27 16:29 UTC
