### ISSUE TITLE
Cannot re-launch editor without refreshing page

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#1] opened 2015-08-03 20:13 UTC
Steps to reproduce:
Log into PA account and navigate to Play Area
Choose a question bank
Click "Edit" button on  one of the problems
Close the editor
click the "Edit" button again - on either the same or another problem

Result: the "Edit" button that was clicked appears grayed out - the editor does not launch
Only refreshing the page or exiting and returning to page allows the editor to re-open.
You should be able to launch the editor multiple times without refreshing the Arrange page

**Comment by Reinmar** [comment] 2015-08-11 15:16
There's an error thrown all the time which blocks closing the popup and breaks some other features:

```
Uncaught TypeError: Cannot read property 'match' of undefined(anonymous function) @ 
```

I cannot reproduce this error locally, but most likely I fixed it in 9306e4d. There's a chance that it will solve this issue.

**Comment by gzip-pa** [comment] 2015-08-12 16:51
There's a slight change improvement in behavior but this is still a bug. 
Now only problems that were previously opened for editing cannot be re-opened prior to refreshing the page:
choose a question bank
click the 'edit' button in one of the problems
cancel the edit
click the edit button on the same problem you just opened
Result: the edit button  on the problem becomes grayed out and nothing else happens.

**Comment by Reinmar** [comment] 2015-08-14 13:04
I don't see any error on the console, so I think that this is an issue with your application, which I cannot debug.

**Comment by gcortright** [comment] 2015-08-14 16:41
@Reinmar, The application code which interacts with the editor has not changed, only the editor has. It is possible, however, that the new editor is expecting something different in terms of data than the old editor, which would be something we would need some guidance about.

**Comment by gcortright** [comment] 2015-08-14 18:41
@gzip-pa still working out what the issue is here. Sorry will have to refresh between edits of the same problem.

**Comment by Reinmar** [comment] 2015-08-18 08:29
Most of the API has not changed between v3 and v4, however some small changes in the editor behaviour were definitely made as the editor code was refactored.

The biggest problem here is that there's no error in the console and that your code is minified so I cannot read it.

The fact of no error being logged may be caused by two things:

1. Your code uses some `try-catch` which eats the error.
2. The problem is caused by some listener not being executed.

About the first I can't do anything. About the second, it might help if you describe (or show me) how the CKEditor API is used.

I also noticed that the editor actually loads, but the modal dialog is hidden and data isn't loaded into the editor.

**Comment by Reinmar** [comment] 2015-08-18 09:58
PS. There's one thing, which might have changed in v4 (although, I would rather think that it worked in the same way in v3) – there are some problems when working with a hidden editor. That's caused by a broken implementation of a native isContentEditable property and some other aspects of using iframes. It may happen that you encounter some version of this problem. I recommend checking if `setData()` or `CKEDITOR.replace()` are called after the modal dialog is shown.

**Comment by gcortright** [comment] 2015-08-19 18:33
@Reinmar we use the following to instantiate the editor:
```= javascript_include_tag '/javascripts/ckeditor/ckeditor.js'
= javascript_tag 'var stem_editor = CKEDITOR.replace("stem_editor");'
= javascript_tag 'var answer_editor = CKEDITOR.replace("answer_editor");'```
As you can see, we do use CKEDITOR.replace().

Once the editor is instantiated, the following JS snippet is used to control the clearing of previous data from the editor:
```
function editProblem(event) {
  if (event.findElement('a.edit') == null) {
    return false;
  }

  var mode = getDocumentMode();
  if (documentFull() && "select" == mode) {
    showMessage('warning', DOCUMENT_FULL_WARNING);
    return;
  }

  if (event.findElement('a.edit').className.match(/\bdisabled\b/)) {

    event.preventDefault();
    return false;
  }

  var aElem = event.findElement('A');
  var problemElem = event.element().up('.problem');
  var probLinkID = getProblemLinkId(problemElem);
  var url = '/problems/' + probLinkID + '.json';

  var docProbID;
  if ($('problem_list').hasClassName('edit')) {
    // we're on the re-arrange page
    docProbID = problemElem.down('img.thumbnail').id.match(/problem(\d+)/)[1];
  }
  else {
    // we're on the select pages
    docProbID = 0;
  }

  disableIconButton(aElem);
  new Ajax.Request(url, {
    method: 'get',
    onCreate: function() {
      showMessage('info', 'Editing...');
    },
    onFailure: function() {
      showMessage('error', "An error occurred while trying to edit a problem.");
      reenableIconButton(aElem);
      updateButtonsEnabled();
    },
    on0: function() {
      showAbortMessage();
      reenableIconButton(aElem);
      updateButtonsEnabled();
    },
    onSuccess: function(response) {
      var editorElem = $('editor-container');
      // store documentProblemId for use when submitting form
      editorElem.writeAttribute('data-document-problem-id', docProbID);
      editorElem.writeAttribute('data-problem-link-id', probLinkID);

      // set the current tab and clear any undo stack leftover from previous problem edits
      // NOTE calling resetUndo after setting data causes an exception to be thrown in CKEditor. gotta reset first.
      $('editor-container').down('.tabberlive').tabber.tabShow(0);

      var tmp = stem_editor.getData();
      if (tmp != null && tmp != '')
        stem_editor.setData('');    // data sticks around from previous problem
      tmp = answer_editor.getData();
      if (tmp != null && tmp != '')
        answer_editor.setData('');  // need to explicitly clear it so there isn't 1 level of undo

      if (false || !Prototype.Browser.IE) {  // IE can eat a bowl of d###
        stem_editor.resetUndo();
        answer_editor.resetUndo();
      }

      var problem = JSONDeref(response,"problem");

      quickDataFixes(problem);

      // calling setData with null does nothing, but we want it interpreted as setting the editor content to an empty string.
      stem_editor.setData(problem.stem || '');
      answer_editor.setData(problem.answer || '');
      processXFigureHtml(problem.xfigure);
      processProperties(problem.properties);

      stem_editor.on('dataReady',function() {
        if (true || !Prototype.Browser.IE) {  // IE can eat a bowl of d###
          stem_editor.resetUndo();
          stem_editor.resetDirty();
        }
      });
      answer_editor.on('dataReady',function() {
        if (true || !Prototype.Browser.IE) {  // IE can eat a bowl of d###
          answer_editor.resetUndo();
          answer_editor.resetDirty();
        }
      });
      xfigure_dirty = false;
      properties_dirty = false;

      // horizontal centering now acomplished by css only. this should be converted when possible,
      var topCoord = Math.max(15, -50 + (document.viewport.getHeight() - editorElem.getHeight()) / 2);
      editorElem.setStyle({
        top: topCoord + 'px',
      });

      editorElem.setOpacity(0);
      editorElem.show();
      new Effect.Opacity(editorElem, { from: 0, to: 1.0, duration: 0.2 });
      $('lbOverlay').style.display = 'block';

      clearMessage();
      reenableIconButton(aElem);
      updateButtonsEnabled();
    },
    onComplete: function(response) {
      if (response.status < 200 || response.status > 299) {
        return;
      }

      // we attach observers to the loaded form here (instead of in onSuccess)
      // because content isn't updated until onComplete. see http://dev.rubyonrails.org/ticket/2072
      var formElem = $('editor-container').down('form');
      if (formElem != null) {
        formElem.writeAttribute('action', null);
        if ($('editor-container').readAttribute('data-document-problem-id') == 0) {
          formElem.observe('submit', submitEditAndAddForm);
        }
        else {
          formElem.observe('submit', submitEditForm);
        }

        var cancelButtonElem = formElem.down('button.cancel');
        if (cancelButtonElem) {
          cancelButtonElem.observe('click', exitBrowseMode);
        }
      }
    }
  });
  event.stop();
}```

We're not getting the error Ajax response, we're getting the success Ajax response, but you'll notice in the success response, we do call setData() to clear the old data from the editor:
```var tmp = stem_editor.getData();
      if (tmp != null && tmp != '')
        stem_editor.setData('');    // data sticks around from previous problem
      tmp = answer_editor.getData();
      if (tmp != null && tmp != '')
        answer_editor.setData('');  // need to explicitly clear it so there isn't 1 level of undo
```
and again further down:
```
// calling setData with null does nothing, but we want it interpreted as setting the editor content to an empty string.
      stem_editor.setData(problem.stem || '');
      answer_editor.setData(problem.answer || '');
```
You're correct, the editor does load, but that the modal is hidden. If you force it, via the inspector, to display, you'll see the editor is empty of data. So, it seems like the first couple of calls to `setData('')`, at least, are working and it breaks down sometime after. Again, this JS has not changed, only the editor code has.

**Comment by Reinmar** [comment] 2015-08-26 15:36
OK, that wasn't easy, but I debugged it a bit. Fortunately, I recalled that in Prototype the `onSuccess` callback is executed in a try-catch block which swallows errors. And AFAICS in the minified source that happens – an error is thrown there. And I even found what is it:

```
i.message
"Cannot read property 'match' of undefined"
e.stack
undefined
i.stack
"TypeError: Cannot read property 'match' of undefined
    at null.<anonymous> (http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor.js:48802:19)
    at listenerFirer (http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor.js:460:33)
    at CKEDITOR.event.fire (http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor.js:606:35)
    at CKEDITOR.editor.fire (http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor.js:730:40)
    at CKEDITOR.tools.extend.getSnapshot (http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor.js:16179:20)
    at Object.CKEDITOR.plugins.undo.Image (http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor.js:39285:26)
    at Object.UndoManager.save (http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor.js:38864:13)
    at null.<anonymous> (http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor.js:38573:17)
    at listenerFirer (http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor.js:460:33)
    at CKEDITOR.event.fire (http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor.js:606:35)"
```

So it's the same place as before (the getSnapshot listener). I could make this code bulletproof, but the problem is that I can see that editor's API **is used incorrectly**. E.g. there are 4 `setData()` calls when opening the dialog... even though there are only 2 editors there. `editor.setData()` is an asynchronous method and unpredictable things may happen if it's called too often or in a wrong moments.

Anyway, there's a lot of pretty strange code (like `if (true || !Prototype.Browser.IE)`) and rather careless usage of CKEditor's API. It might have worked before, but in such situation you'll never know when it'll break. I will make that listener bulletproof now, but I cannot promise that it will solve all the issues and that something else won't break again.

PS. Could you disable code minification in your assets pipeline? That would make debugging a lot easier.

**Comment by Reinmar** [comment] 2015-08-26 15:43
I pushed 7db0690 with a code that may fix this issue.

**Comment by gcortright** [comment] 2015-08-26 16:59
@Reinmar awesome thank you. I will see get the asset pipeline code unminified and let you know when it is done.

**Comment by gcortright** [comment] 2015-08-26 17:25
@Reinmar I've also pulled your changed above to the server. It helps: the editor is now no longer hidden when relaunched, but the problem data only shows in the editor on every other launch for a problem. No doubt, that is because of the way setData() is being called. 

Anyway, I should have our unminified JS up soon.

**Comment by Reinmar** [comment] 2015-08-27 12:30
I tried to figure out how to fix that `Ajax.request` that you make. It's a bit too much logic for me to rewrite it, but a thing I would propose is to have two variables `stem_data` and `answer_data`, figure out what should be their values during the execution and then call `stem_editor.setData( stem_data ); answer_editor.setData( answer_data );` just once at the very end. That should help.

**Comment by Reinmar** [comment] 2015-08-27 12:33
And one more thing – I've been Prototype user myself, but unfortunately that's an awfully outdated library. And the fact that it swallows errors is terrible too (I only predicted that because I learnt myself how terrible that was :D). I'd recommend starting getting rid of it. Other than issues like this you can also start facing compatibility issues with new browsers (Edge for instance).

**Comment by gcortright** [comment] 2015-08-27 17:39
@Reinmar we are working towards getting off of prototype completely, thank goodness!
I will work on our JS to fix the use of the CkEditor API. Thanks!

**Comment by gcortright** [comment] 2015-08-27 19:08
@gzip-pa Please retest.

**Comment by gcortright** [comment] 2015-08-31 18:45
@gzip-pa please retest

**Comment by Reinmar** [comment] 2015-09-02 13:19
With the new design I get:

```
GET http://www.staging.problem-attic.com/javascripts/ckeditor/ckeditor_source.js 
88221:491 Uncaught ReferenceError: CKEDITOR is not defined(anonymous function) @ 88221:491
88221:496 Uncaught ReferenceError: CKEDITOR is not defined(anonymous function) @ 88221:496
application-35d3aabd23e6819b6749e7d6a245b7f7.js:2 Uncaught TypeError: Cannot read property 'on' of undefinedwaitForEditorReady @ application-35d3aabd23e6819b6749e7d6a245b7f7.js:2t.include.o @ application-35d3aabd23e6819b6749e7d6a245b7f7.js:39v @ application-35d3aabd23e6819b6749e7d6a245b7f7.js:39Object.extend._methodized @ application-35d3aabd23e6819b6749e7d6a245b7f7.js:31e @ application-35d3aabd23e6819b6749e7d6a245b7f7.js:39
```

**Comment by gzip-pa** [comment] 2015-09-02 17:32
I cant reproduce this in staging today

**Comment by gcortright** [comment] 2015-09-02 17:43
@gzip-pa As regards @Reinmar's comment here: https://github.com/educaide/ckeditor-dev/issues/1#issuecomment-137075076: I fixed it. @Reinmar emailed me, in addition to this comment, and I emailed him letting him know it was fixed as well, just didn't comment. Just a matter of switching back from a feature branch. I'm going to close this issue now as fixed.

**Closed by gcortright** 2015-09-02 17:43 UTC
Labels: High, invalid
