### ISSUE TITLE
Problem Editor: Special characters,  geometry line symbols cause display failure

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#34] opened 2015-08-19 17:24 UTC
_From @gzip-pa on June 24, 2015 16:55_

Steps to reproduce:
Create or edit a problem.
Select Symbol > Special Characters> Geometry> one of these:
![bad geometry](https://cloud.githubusercontent.com/assets/12751439/8336153/22d8a1f6-1a57-11e5-9752-8e07a4be33a3.png)
Save the problem.

Result: 
Observe that in both the problem in thumbnail and in the Document Preview, neither the geometry symbol nor any of the following content is displayed in the problem.

_Copied from original issue: educaide/hachiko#441_

**Comment by Reinmar** [comment] 2015-09-09 14:36
This is a screenshot from your production server after I added one of these characters to a question. So this isn't any regression or CKEditor bug (loading the content of that question to CKEditor works fine):

<img width="668" alt="screen shot 2015-09-09 at 16 34 53" src="https://cloud.githubusercontent.com/assets/156149/9764697/c3a8b85a-5710-11e5-8563-478211a12bbf.png">

**Comment by patrickdavey** [comment] 2015-09-14 04:58
The issue here is that the codepoints which were in https://github.com/educaide/hachiko/blob/fixNokogiriCase/app/textranslate/entities.xml#L419-L423 were incorrect and not matching the 120, 130, 140 codepoints.

This has been fixed in https://github.com/educaide/hachiko/pull/569

Please note, again, unless there is trailing chars after these geometry figures they are not printed.  This may be as expected though as it looks like they are supposed to be going "over" some text as it were.

### Screenshot of ckeditors html.
![screen shot 2015-09-14 at 4 55 32 pm](https://cloud.githubusercontent.com/assets/549469/9842393/937b3bb8-5b01-11e5-9df7-b35837262100.png)

### Screenshot of rendered tex
![screen shot 2015-09-14 at 4 55 44 pm](https://cloud.githubusercontent.com/assets/549469/9842396/9bb51db2-5b01-11e5-91dc-b6355f94cb3c.png)


### log
```
This is pdfTeX, Version 3.1415926-2.4-1.40.13 (TeX Live 2012) (format=acc4-pdf 2015.9.14)  14 SEP 2015 04:55
entering extended mode
 %&-line parsing enabled.
**/tmp/d20150914-4495-17g1ajn/4271661-2015-09-14T04-55-38Z.tex
(/tmp/d20150914-4495-17g1ajn/4271661-2015-09-14T04-55-38Z.tex (/srv/www/hachiko
/current/support/texmf/tex/educaide/thumbs.sty
version 4.3.10, format version 4.4.229
)
\openout0 = `4271661-2015-09-14T04-55-38Z.CSV'.


Overfull \hbox (4.32376pt too wide) detected at line 6
$\musyf@nt ^^@ ^^@$
 []

Runaway argument?
! Paragraph ended before \overdashfill@ was complete.
<to be read again> 
                   \par 
l.7 
    
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.

Runaway argument?
! Paragraph ended before \overdashfill@ was complete.
<to be read again> 
                   \par 
l.9 
    
I suspect you've forgotten a `}', causing me to apply this
control sequence to too much text. How can we recover?
My plan is to forget the whole thing and hope for the best.

[1.445.78{/srv/www/hachiko/current/support/texmf/fonts/map/pdftex/updmap/pdftex
.map}] ){/srv/www/hachiko/current/support/texmf/fonts/enc/educaide/texextra2.en
c}</srv/www/hachiko/current/support/texmf/fonts/truetype/educaide/cmr.ttf></usr
/local/texlive/2012/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb></usr/
local/texlive/2012/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy10.pfb>
Output written on /tmp/d20150914-4495-17g1ajn/4271661-2015-09-14T04-55-38Z.pdf 
(1 page, 21154 bytes).
PDF statistics:
 18 PDF objects out of 1000 (max. 8388607)
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)


```

### tex

```
\input thumbs.sty
\begindocument
\beginproblem
strange symbols

before\seg after~\ray

\arc something..\lin

after everything..
\endproblem
\enddocument

```

Looks like it has the same issues with the `\lin` etc coming at the end of a line of tex.  One for Dan to fix in tex from here?

**Comment by patrickdavey** [comment] 2015-09-14 20:48
Assigning to you @gcortright  for review and comment (perhaps by Dan)

**Closed** 2015-11-13 17:42 UTC
Labels: bug
