### ISSUE TITLE
Indent button not working

### ISSUE THREAD

**Issue by gzip-pa** [educaide/ckeditor-dev#20] opened 2015-08-12 23:12 UTC
Steps to reproduce:
Log into PA account and navigate to the Play Area
Select a question bank
Click "Edit" on a problem or write a new one.
Select some text. The "Increase Indent" button on the editor toolbar should become active. It does not.

**Comment by Reinmar** [comment] 2015-08-18 09:30
Since CKE 4.2 the indent functionality has been split into indentlist and indentblock. I enabled only the former. Do you need also the latter? If so, then simply enable the indentblock plugin.

**Comment by gcortright** [comment] 2015-08-19 17:51
@Reinmar included `indentblock` in the build-config, ran a new build and deployed it. Am still able to reproduce the issue.

**Comment by Reinmar** [comment] 2015-08-27 13:04
Perhaps you forgot to add it to your config. You need to keep the build config and the `config.js` files in sync. Alternatively, you can wrap the list of plugins that's now present inside `easconfig.js` with:

```
// %REMOVE_START%
config.plugins = [ ...
// %REMOVE_END%
```

(see the original `config.js` file).

This way, when building the editor that code will be striped so editor will be initialised with all the plugins present in the build config. However, that will cause the dev and prod configs to diverge what'd be bad for debugging. So I rather recommend just keeping them in sync.

**Comment by Reinmar** [comment] 2015-08-27 13:05
I pushed 4d2460f that should fix this issue.

**Comment by Reinmar** [comment] 2015-08-27 16:29
I'm closing this issue to keep the list clean. Reopen if this is still a problem.

**Closed by Reinmar** 2015-08-27 16:29 UTC
